/*
  Warnings:

  - You are about to drop the column `wa_paid` on the `setting_webs` table. All the data in the column will be lost.
  - You are about to drop the column `wa_pending` on the `setting_webs` table. All the data in the column will be lost.
  - You are about to drop the column `wa_process` on the `setting_webs` table. All the data in the column will be lost.
  - You are about to drop the column `wa_success` on the `setting_webs` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE `setting_webs` DROP COLUMN `wa_paid`,
    DROP COLUMN `wa_pending`,
    DROP COLUMN `wa_process`,
    DROP COLUMN `wa_success`,
    ADD COLUMN `waPaid` VARCHAR(191) NULL,
    ADD COLUMN `waPending` VARCHAR(191) NULL,
    ADD COLUMN `waProcess` VARCHAR(191) NULL,
    ADD COLUMN `waSuccess` VARCHAR(191) NULL,
    MODIFY `judul_web` VARCHAR(191) NOT NULL,
    MODIFY `deskripsi_web` VARCHAR(191) NOT NULL,
    MODIFY `keyword` VARCHAR(191) NOT NULL,
    MODIFY `og_image` VARCHAR(191) NULL,
    MODIFY `logo_header` VARCHAR(191) NULL,
    MODIFY `logo_footer` VARCHAR(191) NULL,
    MODIFY `logo_favicon` VARCHAR(191) NULL,
    MODIFY `logo_banner` VARCHAR(191) NULL,
    MODIFY `logo_cs` VARCHAR(191) NULL,
    MODIFY `url_wa` VARCHAR(191) NOT NULL,
    MODIFY `url_ig` VARCHAR(191) NOT NULL,
    MODIFY `url_tiktok` VARCHAR(191) NOT NULL,
    MODIFY `url_youtube` VARCHAR(191) NOT NULL,
    MODIFY `url_fb` VARCHAR(191) NOT NULL,
    MODIFY `kbrstore_api` VARCHAR(191) NOT NULL,
    MODIFY `slogan_web` VARCHAR(191) NOT NULL,
    MODIFY `snk` VARCHAR(191) NOT NULL,
    MODIFY `privacy` VARCHAR(191) NOT NULL,
    MODIFY `warna1` VARCHAR(191) NOT NULL,
    MODIFY `warna2` VARCHAR(191) NOT NULL,
    MODIFY `warna3` VARCHAR(191) NOT NULL,
    MODIFY `warna4` VARCHAR(191) NOT NULL,
    MODIFY `warna5` VARCHAR(191) NOT NULL,
    MODIFY `harga_gold` VARCHAR(191) NOT NULL,
    MODIFY `harga_platinum` VARCHAR(191) NOT NULL,
    MODIFY `tripay_api` VARCHAR(191) NULL,
    MODIFY `tripay_merchant_code` VARCHAR(191) NULL,
    MODIFY `tripay_private_key` VARCHAR(191) NULL,
    MODIFY `duitku_key` VARCHAR(191) NULL,
    MODIFY `duitku_merchant` VARCHAR(191) NULL,
    MODIFY `username_digi` VARCHAR(191) NULL,
    MODIFY `api_key_digi` VARCHAR(191) NULL,
    MODIFY `apigames_secret` VARCHAR(191) NULL,
    MODIFY `apigames_merchant` VARCHAR(191) NULL,
    MODIFY `vip_apiid` VARCHAR(191) NULL,
    MODIFY `vip_apikey` VARCHAR(191) NULL,
    MODIFY `digi_seller_user` VARCHAR(191) NULL,
    MODIFY `digi_seller_key` VARCHAR(191) NULL,
    MODIFY `nomor_admin` VARCHAR(191) NULL,
    MODIFY `wa_key` VARCHAR(191) NULL,
    MODIFY `wa_number` VARCHAR(191) NULL,
    MODIFY `ovo_admin` VARCHAR(191) NULL,
    MODIFY `ovo1_admin` VARCHAR(191) NULL,
    MODIFY `gopay_admin` VARCHAR(191) NULL,
    MODIFY `gopay1_admin` VARCHAR(191) NULL,
    MODIFY `dana_admin` VARCHAR(191) NULL,
    MODIFY `shopeepay_admin` VARCHAR(191) NULL,
    MODIFY `bca_admin` VARCHAR(191) NULL,
    MODIFY `mandiri_admin` VARCHAR(191) NULL,
    MODIFY `logo_ceo` VARCHAR(191) NULL,
    MODIFY `sejarah` VARCHAR(191) NOT NULL,
    MODIFY `sejarah_1` VARCHAR(191) NOT NULL,
    MODIFY `visi` VARCHAR(191) NOT NULL,
    MODIFY `misi` VARCHAR(191) NOT NULL,
    MODIFY `nama_ceo` VARCHAR(191) NOT NULL,
    MODIFY `deskripsi_ceo` VARCHAR(191) NOT NULL,
    MODIFY `nama_bagan` VARCHAR(191) NOT NULL,
    MODIFY `alamat` VARCHAR(191) NOT NULL,
    MODIFY `telp` VARCHAR(191) NOT NULL,
    MODIFY `email` VARCHAR(191) NOT NULL,
    MODIFY `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);
